### ISSUE TITLE
Compare ADL  output from python module against node module output

### ISSUE THREAD

**Issue by pietrop** [bbc/aes31-adl-composer#3]
It be good to run the python module, to get an ADL that can be used to write a test to check agains the output of the refactored node module.

**Comment by pietrop** [comment]
python version: [`edl2aes31.py``](https://github.com/bbc/aes31-adl-composer/blob/master/python-version/edl2aes31.py)
node module: [`src/index.js`](https://github.com/bbc/aes31-adl-composer/blob/master/src/index.js)

**Comment by pietrop** [comment]
Ideally both scripts would take same input json [`/sample-data/sample-input/edits.json`](https://github.com/bbc/aes31-adl-composer/blob/master/sample-data/sample-input/edits.json) 
note this has only been tested with the node module and not with python in this repo.

**Comment by emettely** [comment]
So you want to use the Python to understand what it's doing and duplicate it in Node?

**Comment by emettely** [comment]
in order to run the python, you would need to do this basically:
at the root of the `python-version` folder
```
python3 -m venv venv
pip3 install timecode
source ./venv/bin/activate
```
Once you've done ^
You want to run python REPL:
```
python3
```
and in that you would run
```
from edl2aes31 import *
```
which would import all the functions of the python script.

**Comment by pietrop** [comment]
Ok, cool

how would this deal with the [dependency of the python code (`edl2aes31.py#L31`)](https://github.com/bbc/aes31-adl-composer/blob/master/python-version/edl2aes31.py#L31) ?


```python
from datetime import datetime, timezone
from uuid import uuid1
from timecode import Timecode
from os.path import basename
from zipfile import ZipFile, ZIP_STORED
```

**Comment by pietrop** [comment]
> So you want to use the Python to understand what it's doing and duplicate it in Node?

I want to compare the output of the python module against the node module (that I've written based on the python one) to check that the node one is creating the correct ADL.
First manually, then programmatically with test/jest.

**Comment by pietrop** [comment]
Just leaving a note that to get setup with python 3 I did


added `export PATH="/usr/local/opt/python/libexec/bin:$PATH"` in `.bash_profile`
and then in terminal
```
brew install python
```
```
brew link python
```
```
brew link --overwrite python
```

**Comment by pietrop** [comment]
ok managed to run the python code and generate an ADL

### ADL generated with node
```xml
<ADL>

<VERSION>
	(ADL_ID)	1234
	(ADL_UID)	45f182d0-a25b-11e9-b5ad-419e09e082db
	(VER_ADL_VERSION)	01.02
	(VER_CREATOR)	"Digital Paper Edit"
	(VER_CRTR)	00.01
</VERSION>

<PROJECT>
	(PROJ_TITLE)	"Test edit 1"
	(PROJ_ORIGINATOR)	"Digital Paper Edit"
	(PROJ_CREATE_DATE)	2019-07-09T15:07:31.069Z
	(PROJ_NOTES)	"_"
	(PROJ_CLIENT_DATA)	"test"
</PROJECT>

<SEQUENCE>
	(SEQ_SAMPLE_RATE)	S44100
	(SEQ_FRAME_RATE)	25
	(SEQ_ADL_LEVEL)	1
	(SEQ_CLEAN)	FALSE
	(SEQ_DEST_START)	0/0000
</SEQUENCE>

<SOURCE_INDEX>
	(Index)	1	(F)	"URL:file://localhost/C:/Audio Files/filename1.wav"	BBCSPEECHEDITOR1	_	_	"_"	"_"
	(Index)	2	(F)	"URL:file://localhost/C:/Audio Files/filename2.wav"	BBCSPEECHEDITOR2	_	_	"_"	"_"
</SOURCE_INDEX>

<EVENT_LIST>
	(Entry)	1	(Cut)	I	filename1.wav	1~2	1~2	00:00:30:00/0000	00:00:00:00/0000	00:00:05:00/0000	_	(Rem) NAME "Label1"
	(Entry)	2	(Cut)	I	filename2.wav	1~2	1~2	00:00:36:00/0000	00:00:05:00/0000	00:00:06:00/0000	_	(Rem) NAME "Label2"
</EVENT_LIST>

</ADL>
```
### ADL generated with python 
```xml
<ADL>

<VERSION>
	(ADL_ID)	1234
	(ADL_UID)	1f48b09a-a25b-11e9-b0f4-784f43858ed7
	(VER_ADL_VERSION)	01.02
	(VER_CREATOR)	"BBC Speech Editor"
	(VER_CRTR)	00.01
</VERSION>

<PROJECT>
	(PROJ_TITLE)	"some project title"
	(PROJ_ORIGINATOR)	"BBC Speech Editor"
	(PROJ_CREATE_DATE)	2019-07-09T15:06:26+00:00
	(PROJ_NOTES)	"_"
	(PROJ_CLIENT_DATA)	"test"
</PROJECT>

<SEQUENCE>
	(SEQ_SAMPLE_RATE)	S44100
	(SEQ_FRAME_RATE)	24
	(SEQ_ADL_LEVEL)	1
	(SEQ_CLEAN)	FALSE
	(SEQ_DEST_START)	00:00:00:00/0000
</SEQUENCE>

<SOURCE_INDEX>
	(Index)	1	(F)	"URL:file://localhost/C:/Audio Files/filename1.wav"	BBCSPEECHEDITOR1	_	_	"_"	"_"
	(Index)	2	(F)	"URL:file://localhost/C:/Audio Files/filename2.wav"	BBCSPEECHEDITOR2	_	_	"_"	"_"
</SOURCE_INDEX>

<EVENT_LIST>
	(Entry)	1	(Cut)	I	1	1~2	1~2	00:00:29:23/0000	00:00:00:00/0000	00:00:05:00/0000	_	(Rem) NAME "Label1"
	(Entry)	2	(Cut)	I	2	1~2	1~2	00:00:35:23/0000	00:00:05:00/0000	00:00:06:00/0000	_	(Rem) NAME "Label2"
</EVENT_LIST>

</ADL>

```

side by side comparison using [diffchecker](https://www.diffchecker.com/diff)
![Screen Shot 2019-07-09 at 16 11 17](https://user-images.githubusercontent.com/4661975/60900524-39b36c00-a264-11e9-896f-d572f910fb22.png)

**Comment by pietrop** [comment]
### Key differences
In green output from python script and in red from node. 
```diff
+ python
- node
```

#### `PROJ_CREATE_DATE`
```diff
+(PROJ_CREATE_DATE)	2019-07-09T15:21:15+00:00
-(PROJ_CREATE_DATE)	2019-07-09T15:21:14.035Z
```
#### `SEQ_DEST_START`
```diff
+(SEQ_DEST_START)	00:00:00:00/0000
- (SEQ_DEST_START)	0/0000
```
#### `SOURCE_INDEX`
```diff
<SOURCE_INDEX>
	(Index)	1	(F)	"URL:file://localhost/C:/Audio Files/filename1.wav"	BBCSPEECHEDITOR1	_	_	"_"	"_"
+	(Index)	2	(F)	"URL:file://localhost/C:/Audio Files/filename1.wav"	BBCSPEECHEDITOR2	_	_	"_"	"_"
-    	(Index)	2	(F)	"URL:file://localhost/C:/Audio Files/filename2.wav"	BBCSPEECHEDITOR2	_	_	"_"	"_"
</SOURCE_INDEX>
```

#### `EVENT_LIST`
```diff
<EVENT_LIST>
+	(Entry)	1	(Cut)	I	2	1~2	1~2	00:00:29:24/0000	00:00:00:00/0000	00:00:05:00/0000	_	(Rem) NAME "Label1"
-	(Entry)	1	(Cut)	I	filename1.wav	1~2	1~2	00:00:30:00/0000	00:00:00:00/0000	00:00:05:00/0000	_	(Rem) NAME "Label1"
+	(Entry)	2	(Cut)	I	1	1~2	1~2	00:00:35:24/0000	00:00:05:00/0000	00:00:06:00/0000	_	(Rem) NAME "Label2"
-	(Entry)	2	(Cut)	I	filename2.wav	1~2	1~2	00:00:36:00/0000	00:00:05:00/0000	00:00:06:00/0000	_	(Rem) NAME "Label2"
</EVENT_LIST>
````

**Comment by pietrop** [comment]
started a PR https://github.com/bbc/aes31-adl-composer/pull/4

**Comment by pietrop** [comment]
Leaving a few notes here about python module vs node script:

- in `edit.json` input file, the file name is called differently in python module vs the node script. This is because the node script uses same input sequence as the [`edl_composer`](https://www.npmjs.com/package/edl_composer) module
- `path` attribute is also not present in the node script. The python module uses the `path` to bundle the files, as zipped with the ADL. To make it work client side this can be removed, and SADiE would look for the files in the current workspace.

````diff
  {
        "start": 30,
        "end": 35,
+       "filename": "filename1.wav",
-        "clipName": "filename1.wav",
        "label": "Label1",
+        "path": "some/path/to/audio/file"
    },
```

```diff
+ python
- node
```

**Comment by pietrop** [comment]
addressed in https://github.com/bbc/aes31-adl-composer/pull/4
